config/routes.rb
Rails.application.routes.draw do

    resources :unicorns

    resources :locations
    
  # get 'locations/index'

  # get 'locations/show'

  # get 'locations/new'

  # get 'locations/create'

  # get 'unicorns/index'

  # get 'unicorns/show'

  # get 'unicorns/new'

  # get 'unicorns/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :unicorns

end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
    belongs_to :location

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

 def show
    @unicorns = Unicorn.all
    @locations = Location.all
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    Location.create(location_params)
    redirect_to('/locations')
  end

  private

  def location_params
    params.require(:location).permit(:name, :image_url)
  end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController
  def index
    @unicorns = Unicorn.all
    @locations = Location.all
  end

  def show
    @unicorns = Unicorn.all
    @locations = Location.all
    @unicorn = Unicorn.find(params[:id])
    @locationid = @unicorn.location_id
    @location = Location.find(@locationid)
  end

  def edit
    @unicorn = Unicorn.find(params[:id])
    @locations = Location.all
    @locationid = @unicorn.location_id
    @location = Location.find(@locationid)
  end

  def update
    @unicorn = Unicorn.find(params[:id])
    @locations = Location.all
    @locationid = @unicorn.location_id
    @location = Location.find(@locationid)

    @unicorn.update_attributes(unicorn_params)
        if @unicorn.update(unicorn_params)
            flash[:notice] = 'Unicorn moved.'
            logger.debug "The unicorn was updated and is now being redirected"
            redirect_to('/unicorns')
        else
            render :edit
        end
  end


  def new
    @unicorn = Unicorn.new
  end

  def create
    Unicorn.create(unicorn_params)
    redirect_to('/unicorns')
  end

  private

  def unicorn_params
    params.require(:unicorn).permit(:name, :gender, :favorite_food, :color, :location_id, :image_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/unicorn_helper.rb
module UnicornHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnicornRancher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Unicorn Locator</h1>
<div id="background">
    <img src="http://img08.deviantart.net/6853/i/2012/158/2/f/pony_scenery_1_by_midnytesketch-d52owoa.png" alt="pasture background">
</div>
<div id="content">
    <% @locations.each do | location | %>
        <h3>Unicorns in the <%= link_to location.name, location_path(location) %>:</h3>
        <ul>
            <% location.unicorns.each do | unicorn | %>
               <li><%= unicorn.name  %></li>
            <% end %>
        </ul>
    <% end %>
</div>
<footer>
    <hr>
    <%= link_to "Unicorns", unicorns_path %>
    <p><strong>The Ranch is Growing!</strong> <%= link_to "Add a Location", new_location_path %></p>
</footer>

app/views/locations/new.html.erb
<h1>Add a Location!</h1>

<div id="background">
    <img src="http://vignette2.wikia.nocookie.net/mlp/images/f/f4/Ponyville_Clocktower_S02E17.png/revision/latest?cb=20121130195624" alt="empty background">
</div>

<div id="content">

    <%= form_for @location do | f | %>
        <span>Location Name: </span>
        <%= f.text_field :name, required: true %><br />
        <span>Image Url: </span>
        <%= f.text_field :image_url, required: true %><br />
        <%= f.submit %>
    <% end %>

</div>
<footer>
    <hr>
    <%= link_to "Unicorns", unicorns_path %><br>
    <%= link_to "Locations", locations_path %>
    <br>
    <p><small>Location images should be approximately 900 pixels wide x 500 pixels tall. <br />
    Illustration style should be consistent with the rest of the ranch. <br />
    These are background images, so please make sure there are no characters or watermarks in the scene.</small></p> 
</footer>

app/views/locations/show.html.erb
<h1><%= @location.name %> Life</h1>

<div id="background">
    <img src="<%= @location.image_url %>" alt="<%= @location.name %>" width="100%" />
</div>
 <div id="unicorns">   
    <% @unicorns.each do | unicorn | %>
        <%  if unicorn.location_id == @location.id  %>
               <img src="<%= unicorn.image_url %>" alt="<%= unicorn.name %>" width="150px" />
        <% end %>
    <% end %>
</div>
<div id="content">
    
</div>
<footer>
    <hr>
    <% if @location.id > 1 && @location.id < @locations.count %>
        <%= link_to "Previous", location_path(@location.id - 1) %>
        <%= link_to "Next", location_path(@location.id + 1) %>
    <% elsif @location.id == @locations.count %>
        <%= link_to "Previous", location_path(@location.id - 1) %>
        <%= link_to "Next", location_path(1) %>
    <% elsif @location.id == 1 %>
        <%= link_to "Previous", location_path(@locations.count) %>
        <%= link_to "Next", location_path(@location.id + 1) %>
    <% end %>
    <br>
    <%= link_to "Unicorns", unicorns_path %><br />
    <%= link_to "Locations", locations_path %>
</footer>
   

app/views/unicorns/edit.html.erb
<h1><%= @unicorn.name %></h1>
<div id="background">
    <img src="http://img04.deviantart.net/a473/i/2012/142/1/4/ponies_fly_by_background_by_adcoon-d50ohmb.png" alt="empty background">
</div>

<div id="content">
    <p><%= @unicorn.name %> was in the <%= @location.name %></p>
    <h2>Where did <%= @unicorn.name %> go?</h2>
        <%= form_for @unicorn do | f | %>
            <% @locations.each do |location| %>
                <%= f.radio_button :location_id, location.id  %><%= location.name %><hr>
            <% end %>
        <%= f.submit %>
    <% end  %>
</div>

<footer>
    <hr>
    <%= link_to "Unicorns", unicorns_path %><br>
    <%= link_to "Locations", locations_path %>
</footer>

app/views/unicorns/index.html.erb
<h1>Equestria Unicorn Rancher</h1>

<div id="background">
    <img src="https://s-media-cache-ak0.pinimg.com/originals/61/e5/52/61e55261b7fa2e0081fdf83d705c1893.jpg" alt="Equestria">
</div>

<div id="content">
    <% @unicorns.each do | unicorn | %>
        <h3><%= unicorn.name %> is in the <%= @locations.find(unicorn.location_id).name %></h3>
        <%= link_to "Show", unicorn_path(unicorn) %>
    <% end %>
    
</div>

<footer>
    <hr>
    <%= link_to "Locations", locations_path %>
    <p><strong>The Herd is Growing!</strong> <%= link_to "Add a Unicorn!", new_unicorn_path %></p>
</footer>

app/views/unicorns/new.html.erb
<h1>Add a Unicorn!</h1>
<div id="background">
    <img src="http://static2.wikia.nocookie.net/my-little-pony-postacie/pl/images/5/50/Wiki-background" alt="empty background">
</div>

<div id="content">
 
    <%= form_for @unicorn do | f | %>
        <span>Unicorn Name: </span>
        <%= f.text_field :name, required: true %><br />
        <span>Gender: </span>
        <%= f.text_field :gender, required: true %><br />
        <span>Favorite Food: </span>
        <%= f.text_field :favorite_food, required: true %><br />
        <span>Color: </span>
        <%= f.text_field :color, required: true %><br />
        <span>Image Url: </span>
        <%= f.text_field :image_url, required: true %><br />
        <%= f.hidden_field :location_id, :value => 1 %>
        <%= f.submit %>
    <% end %>  
</div>

<footer>
    <hr>
    <%= link_to "Unicorns", unicorns_path %><br>
    <%= link_to "Locations", locations_path %>
    <br>
    <p><small>Unicorn images should be approximately 150 - 300 pixels wide.<br />
    Illustration style should be consistent with the rest of the ranch. <br />
    Please use only .PNG images with a transparent background and no watermarks.</small></p>  
</footer>

app/views/unicorns/show.html.erb
<h1><%= @unicorn.name %></h1>
<div id="background">
    <img src="http://wallpapercave.com/wp/ildJ2CY.jpg" alt="rainbow background" />
</div>

<div id="content">
    <p><%= @unicorn.name %> is in the <%= @location.name %></p>
    <ul>
            <li><strong>Gender:</strong> <%= @unicorn.gender %></li>
            <li><strong>Fave Food:</strong> <%= @unicorn.favorite_food %></li>
            <li><strong>Color:</strong> <%= @unicorn.color %></li>
        </ul>
    <img src="<%= @unicorn.image_url %>" alt="<%= @unicorn.name %>" width="200px" />
    <br />    
    <%= link_to "Move Me", edit_unicorn_path(@unicorn) %>
</div>

<footer>
    <hr>
    <% if @unicorn.id > 1 && @unicorn.id < @unicorns.count %>
        <%= link_to "Previous", unicorn_path(@unicorn.id - 1) %>
        <%= link_to "Next", unicorn_path(@unicorn.id + 1) %>
    <% elsif @unicorn.id == @unicorns.count %>
        <%= link_to "Previous", unicorn_path(@unicorn.id - 1) %>
        <%= link_to "Next", unicorn_path(1) %>
    <% elsif @unicorn.id == 1 %>
        <%= link_to "Previous", unicorn_path(@unicorns.count) %>
        <%= link_to "Next", unicorn_path(@unicorn.id + 1) %>
    <% end %>
    <br>
    <%= link_to "Locations", locations_path %><br />
    <%= link_to "Unicorns", unicorns_path %>
</footer>